### PR TITLE
Tile 2025 Validation 

### PR DESCRIPTION
**Pull request by jaredsnyder**
Due to time constraints the validation report was written after the 2025 numbers were handed off.  A few minor bugs were found and the numbers were updated.  The README was also improved and some variable names changed for readability

Validation doc: https://docs.google.com/document/d/1JFPLuBwSsO-1C76vhA_mGStfmHzEkTyMmQ3drYrOiHo/edit?tab=t.0

### CODE REVIEW

**Review by sergiosonline — APPROVED** [review]
Thanks for adding all this context via the flow diagram and the expanded descriptions. We'll definitely iterate on the language going forward.

**Comment by sergiosonline** [comment]
The verbiage in the diagram isn't totally accurate. It's not scalar multiplication throughout, but rather matrix dot product. Also, for the average operations, we average over a specific dimension, not all of them. So it's worthwhile calling those out. Cause scalar multiplication against a vector / matrix, means that all entries of said vector / matrix are getting multiplied by the exact same quantity.

**Comment by jaredsnyder** [comment]
It's accurate if you consider each country's data independently.  Each country is a 1-d timeseries, when we average it is exclusively over the time component.  I think that is a better way to represent it than as matrix multiplication because we don't represent the data as a matrix in the code, we represent it as a dataframe we subset by country to get 1-d timeseries (or groups of 1-d timeseries that we aggregate over time).  There isn't any matrix math in the code so it would be confusing to represent it that way.  I can improve the diagram to make this more clear

**Comment by sergiosonline** [comment]
Yeah, that's fair. I'd suggest adding some clarification in the diagram as a header like like: For each country $i$ that we'd like to forecast, we...

**Pull request merged**
